config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :welcome, only: [:index]
  resources :users
  resources :sessions
  resources :books
  resources :receptions, only: [] do
    collection do
      get :new_take_book
      get :new_return_book
      post :take_book
      post :return_book
    end

  end

  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'login' => 'sessions#new', :as => 'login'
  
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :name, presence: true, length: { minimum: 2, maximum: 255 }, uniqueness: true
  validates :author_name, presence: true, length: { minimum: 2, maximum: 255 }

  enum status: { available: 0, unavailable: 1 }

  scope :latest, -> { order(created_at: :desc) }

  scope :with_status, -> (status) { where(status: status) if statuses.keys.include?(status) }

  before_destroy do
    throw :abort if unavailable?
  end
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :imageable, polymorphic: true
  mount_uploader :picture, PictureUploader
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  has_many :books
  has_one :picture, as: :imageable, dependent: :destroy

  validates :email, presence: true, uniqueness: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }

  validates :first_name, length: { minimum: 2, maximum: 25 }
  validates :last_name, length: { minimum: 2, maximum: 25 }

  scope :with_books, -> { joins(:books) }

  enum role: { regular: 0, admin: 1 }
  accepts_nested_attributes_for :picture

  before_destroy do
    throw :abort if books.present?
  end

  def picture
    super || build_picture
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def has_avatar?
    !picture.new_record?
  end

  def avatar_url
    picture.picture.url
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :require_login

  private

  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    @books = Book.with_status(params[:status]).includes(:user).order('books.name')
  end

  def show
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to book_path(@book), notice: 'book successfully created'
    else
      redirect_to new_book_path, alert: @book.errors.full_messages.join(', ')
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to book_path, notice: 'book successfully updated'
    else
      redirect_back_or_to(book_path(@book), alert: 'Can not update the book')
    end
  end

  def destroy
    if @book.destroy
      redirect_to books_path, notice: 'book successfully deleted'
    else
      redirect_to book_path(@book), alert: 'Can not delete the book'
    end
  end

  private

  def book_params
    params.require(:book).permit(:name,
                                 :author_name,
                                 :description)
  end

  def set_book
    @book = Book.find(params[:id])
  end
end

app/controllers/receptions_controller.rb
class ReceptionsController < ApplicationController
  before_filter :set_book, only: [:take_book, :return_book]
  def new_take_book
    @books = Book.available.order('name asc').pluck(:name, :id)
    @users = User.regular.order('first_name asc').pluck(:email, :id)
  end

  def new_return_book
    @books = Book.unavailable.order('name asc').pluck(:name, :id)
  end

  def take_book
    redirect_to :back , alert: 'Choose user' and return if params[:user_id].blank?
    @book.update(user_id: params[:user_id], status: :unavailable)
    redirect_to new_take_book_receptions_path, notice: 'Book has been successfully taken'
  end

  def return_book
    @book.update(user_id: nil, status: :available)
    redirect_to new_return_book_receptions_path, notice: 'Book has been successfully returned'
  end


  private

  def set_book
    redirect_to :back , alert: 'Choose book' and return if params[:book_id].blank?
    @book = Book.find(params[:book_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  def new
  end

  def create
    redirect_to login_path, alert: 'Invalid user' and return if regular_user?
    if login(params[:email], params[:password])
      redirect_to root_path, notice: 'Logged in successfully'
    else
      redirect_to login_path, alert: 'Email or password invalid'
    end
  end

  def destroy
    logout
    redirect_to root_path, notice: 'Logged out successfully'
  end

  private

  def regular_user?
    user = User.find_by(email: params[:email])
    return unless user
    user.regular?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :update, :edit, :destroy]

  def index
    @users = User.regular.includes(:books).order(:first_name)
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_path(@user), notice: 'User successfully created'
    else
      redirect_to new_user_path, alert: @user.errors.values.join(', ')
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path, notice: 'User successfully updated'
    else
      redirect_back_or_to(user_path(@user), alert: 'Can not update the user')
    end
  end

  def destroy
    if @user.destroy
      redirect_to users_path, notice: 'User successfully deleted'
    else
      redirect_to user_path(@user), alert: 'Can not delete the user'
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :email,
                                 picture_attributes: picture_attributes
    )
  end

  def picture_attributes
    [:picture, :id]
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @welcome_stat = WelcomePageService.new.call
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  BOOK_STATUSES = {
      all_books: 'all',
      available_books: 'available',
      unavailable_books: 'unavailable'
  }

  def menu_item_class(item)
    if params[:controller] == item
      return 'active'
    end

    if params[:controller] == 'books' && BOOK_STATUSES[item.to_sym] == params[:status] && BOOK_STATUSES[item.to_sym].present?
      'active'
    end
  end

  def bootstrap_class_for flash_type
    { success: "alert-success",
      alert: "alert-danger",
      notice: "alert-info"
    }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in text-center") do
        concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
        concat message
      end)
    end
    nil
  end

  def current_admin
    current_user
  end
end

app/views/books/_form.slim
= bootstrap_form_for @book, html: {class: 'width-col-xs-6 centered create-book-form'} do |f|
  = f.text_field :name, placeholder: 'Book name', minlength: 2, maxlength: 255
  = f.text_field :author_name, placeholder: 'Author name', minlength: 2, maxlength: 255
  = f.text_area :description, placeholder: 'Book description', minlength: 10, maxlength: 6555
  = link_to 'Cancel', books_path, class: 'btn btn-danger cancel-btn'
  = f.submit class: 'btn btn-success'

app/views/books/edit.slim
.row
  h1.text-center Edit Book
  = render 'form'

app/views/books/index.slim
.row
  h2 Books:
  - if @books.present?
    table.table.table-striped
      thead
        tr
          th Id
          th Name
          th Author Name
          th User
          th Status
          th
      tbody
        - @books.each do |book|
          tr
            td = book.id
            td = link_to book.name, book_path(book)
            td = book.author_name
            td
              - if book.unavailable? && book.user.present?
                = link_to book.user.first_name, user_path(book.user)
            td = book.status.humanize
            td
              = link_to '', edit_book_path(book), class:'glyphicon glyphicon-pencil'
              - if book.available?
                = link_to '',
                        book_path(book),
                        method: :delete,
                        'data-confirm' => 'Are you sure?',
                        class: 'glyphicon glyphicon-trash delete-book'
  - else
    h4.text-center There are no books yet

app/views/books/new.slim
.row
  h1.text-center Create Book
  = render 'form'

app/views/books/show.slim
.row
  h1.text-center = @book.name
  = @book.description
  hr
  p
    b Author name:
    = ' ' + @book.author_name

  - if @book.unavailable? && @book.user.present?
    p
      b Taken by:
      = link_to ' ' + @book.user.full_name, user_path(@book.user)

app/views/layouts/application.slim
doctype html
html lang="en"
  head
    meta charset="utf-8" /
    meta content="IE=edge" http-equiv="X-UA-Compatible" /
    meta content="width=device-width, initial-scale=1" name="viewport" /
    meta content="Library" name="description" /
    meta content="Vladislav Beliaiev" name="author" /
    title Library
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag('favicon.png')
    link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" /
    link href="https://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css" /
  body
    nav.navbar.navbar-inverse.navbar-static-top
      .container
        .navbar-header
          = link_to 'Library', root_path, class:'navbar-brand'
        #navbar.navbar-collapse.collapse
          - if current_admin
            ul.nav.navbar-nav
              li class = "#{menu_item_class('welcome')}"
                = link_to 'Home', root_path
              li class = "#{menu_item_class('users')}"
                =link_to 'Users', users_path
              li class = "#{menu_item_class('all_books')}"
                =link_to 'Books', books_path(status: 'all')
              li class = "#{menu_item_class('available_books')}"
                = link_to 'Available Books', books_path(status:'available')
              li class = "#{menu_item_class('unavailable_books')}"
                = link_to 'Unavailable Books', books_path(status:'unavailable')
          ul.nav.navbar-nav.pull-right
            - if current_admin
              = link_to 'Take Book',
                      new_take_book_receptions_path,
                      class: 'btn btn-info pull-left create-item-btn-menu create-user'

              = link_to 'Return Book',
                      new_return_book_receptions_path,
                      class: 'btn btn-info pull-left create-item-btn-menu create-user'

              = link_to 'Create User', new_user_path, class: 'btn btn-success pull-left create-item-btn-menu create-user'
              = link_to 'Create Book', new_book_path, class: 'btn btn-success pull-left create-item-btn-menu'
              li
                = link_to 'Log Out', logout_path
            - else
              li
                = link_to 'Log In', login_path
    .container.theme-showcase.main-container
      .row
        = flash_messages
      = yield

app/views/receptions/new_return_book.slim
.row
  h2.text-center Return a book
  = bootstrap_form_tag url: return_book_receptions_path, html: { class: 'width-col-xs-6  centered' } do |f|
    = f.select :book_id, @books, {}, { class: 'js-select-books' }
    = link_to 'Cancel', users_path, class: 'btn btn-danger cancel-btn'
    = f.submit class: 'btn btn-success'

app/views/receptions/new_take_book.slim
.row
  h2.text-center Take a book
  = bootstrap_form_tag url: take_book_receptions_path, html: { class: 'width-col-xs-6  centered' } do |f|
    = f.select :user_id, @users, { label:'User email'}, { class: 'js-select-users', id: 'select-users' }
    = f.select :book_id, @books, {}, { class: 'js-select-books' }
    = link_to 'Cancel', users_path, class: 'btn btn-danger cancel-btn'
    = f.submit class: 'btn btn-success'

app/views/users/_form.slim
= bootstrap_form_for @user, html: {class: 'width-col-xs-6  centered'}, multipart: true do |f|
  = f.text_field :first_name, placeholder: 'First name', minlength: 2, maxlength: 255
  = f.text_field :last_name, placeholder: 'Last name', minlength: 2, maxlength: 255
  = f.text_field :email, placeholder: 'Email', minlength: 2, maxlength: 255
  = f.fields_for :picture do |pic|
    = pic.file_field :picture, label: 'Avatar'
  = link_to 'Cancel', users_path, class: 'btn btn-danger cancel-btn'
  = f.submit class: 'btn btn-success'

app/views/users/edit.slim
.row
  h2.text-center Edit user
  = render 'form'

app/views/users/index.slim
.row
  h2 Users:
  - if @users.present?
    table.table.table-striped
      thead
        tr
          th Id
          th Full Name
          th Email
          th Role
          th
      tbody
        - @users.each do |user|
          tr
            td = user.id
            td = link_to user.full_name, user_path(user)
            td = user.email
            td = user.role.humanize
            td
              = link_to '', edit_user_path(user), class:'glyphicon glyphicon-pencil'
              - unless user.books.present?
                = link_to '',
                        user_path(user),
                        method: :delete,
                        'data-confirm' => 'Are you sure?',
                        class: 'glyphicon glyphicon-trash delete-user'

  - else
    h4.text-center There are no users yet

app/views/users/new.slim
.row
  h2.text-center New user
  = render 'form'

app/views/users/show.slim
.row
  .user-info.text-center
    - if @user.has_avatar?
      = image_tag @user.avatar_url, class: 'user-avatar'
    h2 = @user.full_name
    h4
      i = @user.email
  hr
  .taken_books
    h2.text-center Taken book(s):
    - if @user.books.present?
      table.table.table-striped
        thead
          tr
            th Id
            th Name
            th Author Name
        tbody
          - @user.books.each do |book|
            tr
              td = book.id
              td = link_to book.name, book_path(book)
              td = book.author_name
    - else
      h4.text-center
        i No taken books

app/views/welcome/index.slim
.row
  h2.text-center Books
  .col-xs-4.text-center
    h4 Total count
    h2.text-info = @welcome_stat.books_count
  .col-xs-4.text-center
    h4 Available books
    h2.text-success = @welcome_stat.available_books_count
  .col-xs-4.text-center
    h4 Unavailable Books
    h2.text-danger = @welcome_stat.unvailable_books_count
  hr
hr
.row
  h2.text-center Users
  .col-xs-6.text-center
    h4 Total count:
    h2.text-info = @welcome_stat.users_count
  .col-xs-6.text-center
    h4 Users with books:
    h2.text-success = @welcome_stat.user_with_books